# Este archivo configura cómo será nuestro cluster local
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mlops-cluster  # Nombre de nuestro cluster

nodes:
- role: control-plane  # Este será el nodo principal que controla el cluster
  extraPortMappings:  # Configuración para acceder a servicios desde fuera del cluster
  - containerPort: 8000  # Puerto dentro del cluster
    hostPort: 8000      # Puerto en tu máquina local
    protocol: TCP       # Protocolo de red
  - containerPort: 4200
    hostPort: 4200
    protocol: TCP
  extraMounts:  # Montaje de volúmenes para persistencia de datos
  - hostPath: ./shared-data    # Carpeta en tu máquina local
    containerPath: /data       # Ruta dentro del cluster