apiVersion: v1
kind: Namespace
metadata:
  name: mlops
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlops-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-training
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-training
  template:
    metadata:
      labels:
        app: mlops-training
    spec:
      containers:
      - name: mlops
        image: mlops-training:latest
        ports:
        - containerPort: 8000
        - containerPort: 4200
        volumeMounts:
        - name: mlops-storage
          mountPath: /app/data
        env:
        - name: DAGSHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlops-secrets
              key: username
        - name: DAGSHUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlops-secrets
              key: password
        - name: GOOGLE_DRIVE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: mlops-secrets
              key: gdrive-creds
      volumes:
      - name: mlops-storage
        persistentVolumeClaim:
          claimName: mlops-pvc