apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-training-config
  namespace: ml-namespace
data:
  DAGSHUB_USERNAME: "auditoria.SGBA1"
  DAGSHUB_REPO_NAME: "SGBA1-smartgrids"

---
apiVersion: v1
kind: Secret
metadata:
  name: ml-training-secrets
  namespace: ml-namespace
type: Opaque
data:
  DAGSHUB_TOKEN: "OTA3OWZlYWFmNWZhNTk4NjEwN2U4NzUzYTg3MTJlY2FkOGU4YTQ3Ng=="
  PREFECT_API_KEY: "cG51X3hhMlhDcHhYbHVkV1ZJOGJpcDFDc1VSaGxqWEQ1cTFxaGNuWA=="
