apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelo-ml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modelo-ml
  template:
    metadata:
      labels:
        app: modelo-ml
    spec:
      containers:
      - name: modelo-ml
        image: tu-imagen-en-dockerhub
        ports:
        - containerPort: 8000
